# FROM almalinux:9
# ARG user="santhosh"
# RUN echo "hello ${user}" > hello.txt

ARG version
FROM almalinux:${version:-9}
ARG user=santhosh
RUn echo "hello ${user}" > hello.txt









# FROM almalinux:9
# ARG username="sk datti"
# ENV username=$username
