FROM almalinux:9
RUN dnf install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
ADD https://raw.githubusercontent.com/santhoshdatti28/dockerfiles/refs/heads/main/COPY/index.html /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]